version: '3.8'

services:
  db:
    image: postgres:15
    container_name: card-db-postgres
    environment:
      POSTGRES_DB: card_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: card-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/card_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_ENABLED: true
      APP_JWT_SECRET: ${APP_JWT_SECRET:-1fYouSeeThis1nProdJustDontLookAtAlsoDontTellLeadHeWillBe7ad}
      APP_ENCRYPTION_KEY: ${APP_ENCRYPTION_KEY:-IfYouSeeThisInProdJustDontLookAt}

volumes:
  postgres-data: