server:
  port: 8080

spring:
  application:
    name: card-management-system

  datasource:
    url: jdbc:postgresql://localhost:5433/card_db
    username: local
    password: local
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

app:
  jwt:
    secret: 1fYouSeeThis1nProdJustDontLookAtAlsoDontTellLeadHeWillBe7ad
    expiration-ms: 86400000
    refresh-token:
      # 7 дней = 604800000 мс
      duration-ms: 604800000
  encryption:
    key: IfYouSeeThisInProdJustDontLookAt